kind: ConfigMap
apiVersion: v1
metadata:
  name: daskernetes-config
data:
  worker-template.yaml: |-
    metadata:
      annotations:
        iam.amazonaws.com/role: "arn:aws:iam::536099501702:role/pangeo"
    spec:
      restartPolicy: Never
      containers:
        - name: dask-worker
          image: {{ .Values.pangeo.jupyterhub.singleuser.image.name }}:{{ .Values.pangeo.jupyterhub.singleuser.image.tag }}
          args: [dask-worker, --nthreads, '1', --no-bokeh, --memory-limit, 6GB, --death-timeout, '60']
          resources:
            limits:
              cpu: "1"
              memory: 6G
            requests:
              cpu: "1"
              memory: 6G
          nodeSelector:
            kubernetes.io/role: agent
            beta.kubernetes.io/os: linux
            type: virtual-kubelet
          tolerations:
          - key: virtual-kubelet.io/provider
            operator: Exists
          - key: azure.com/aci
            effect: NoSchedule