sudo: required

language: python
python:
  - '3.6'

install:
  - $TRAVIS_BUILD_DIR/scripts/setup.sh

script:
  - bash $TRAVIS_BUILD_DIR/scripts/test-chart.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh dev pangeo-dev.informaticslab.co.uk pangeo-dev
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh prod jupyterhub.informaticslab.co.uk jupyter
    on:
      tags: true
