kind: ConfigMap
apiVersion: v1
metadata:
  name: telegraf-config
data:
  telegraf.conf: |-
    [global_tags]

    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      debug = false
      quiet = false
      hostname = ""
      omit_hostname = false

    [[outputs.influxdb]]
      urls = ["$INFLUX_DB_INGEST_URL"]
      database = "telegraf"
      precision = "s"
      write_consistency = "any"
      timeout = "5s"
      username="$INFLUX_DB_INGEST_USER"
      password="$INFLUX_DB_INGEST_PASS"
